"""Candidate design generation."""

from __future__ import annotations

import math
import random
import uuid

from mini_tokamak.schemas import Candidate, DesignSpaceConfig, RangeSpec


def sample_range(rng: random.Random, spec: RangeSpec) -> float:
    return rng.uniform(spec.min, spec.max)


def plasma_volume(R: float, a: float, kappa: float) -> float:
    return 2.0 * math.pi**2 * R * a**2 * kappa


def estimated_machine_volume(
    R: float, a: float, kappa: float, shield_thickness: float, first_wall_thickness: float
) -> float:
    outer_radius = R + a + shield_thickness + first_wall_thickness
    half_height = kappa * a + shield_thickness + first_wall_thickness
    return math.pi * outer_radius**2 * (2.0 * half_height)


def generate_candidate(space: DesignSpaceConfig, rng: random.Random | None = None) -> Candidate:
    rng = rng or random.Random()

    machine_type = rng.choice(space.machine_type)
    fuel_mode = rng.choice(space.fuel_modes)

    # Sample aspect ratio first and derive minor radius when possible. This keeps most
    # generated designs internally meaningful while still leaving room for failures.
    aspect_ratio = sample_range(rng, space.aspect_ratio_A)
    R = sample_range(rng, space.major_radius_R_m)
    a = R / aspect_ratio
    if not space.minor_radius_a_m.contains(a):
        a = sample_range(rng, space.minor_radius_a_m)
        aspect_ratio = R / a

    kappa = sample_range(rng, space.elongation_kappa)
    delta = sample_range(rng, space.triangularity_delta)
    Bt = sample_range(rng, space.toroidal_field_Bt_T)
    Ip = sample_range(rng, space.plasma_current_Ip_MA)
    heating_power = sample_range(rng, space.heating_power_MW)
    shield = sample_range(rng, space.shield_thickness_m)
    first_wall = sample_range(rng, space.first_wall_thickness_m)
    center_column = sample_range(rng, space.center_column_radius_m)

    return Candidate(
        candidate_id=str(uuid.uuid4()),
        machine_type=machine_type,
        fuel_mode=fuel_mode,
        R=R,
        a=a,
        aspect_ratio=aspect_ratio,
        kappa=kappa,
        delta=delta,
        Bt=Bt,
        Ip=Ip,
        heating_power=heating_power,
        shield_thickness=shield,
        first_wall_thickness=first_wall,
        center_column_radius=center_column,
        estimated_volume=estimated_machine_volume(R, a, kappa, shield, first_wall),
        estimated_plasma_volume=plasma_volume(R, a, kappa),
        notes="Generated by random low-fidelity design-space sampler.",
    )


def generate_candidates(
    space: DesignSpaceConfig, n: int, seed: int | None = None
) -> list[Candidate]:
    rng = random.Random(seed)
    return [generate_candidate(space, rng) for _ in range(n)]

